name: Send mail
uses: dawidd6/action-send-mail@v3
with:
  # Required mail server address:
  server_address: smtp.gmail.com
  # Required mail server port:
  server_port: 465
  # Required mail subject:
  subject: Github Actions job result
  # Required recipients' addresses:
  to: adolf.schmuck@gmail.com
  # Required sender full name (address can be skipped):
  from: Luke Skywalker
  # Optional plain body:
  body: Build job of ${{github.repository}} completed successfully!
  # Optional priority: 'high', 'normal' (default) or 'low'
  priority: low
